---
- name: Create concourse directory
  file:
    state: directory
    path: /opt/concourse/
  tags:
    - directory
    - setup
- group:
    name: concourse
    state: present
- user:
    name: concourse
    group: concourse
- name: Download Concourse Binary
  get_url:
    url: "https://github.com/concourse/concourse/releases/download/v1.1.0/concourse_linux_amd64"
    checksum: sha1:11ee11f880fdf7791adead50699e83c61cdd9bc3
    dest: /opt/concourse/
    mode: 775
    owner: concourse
    group: concourse
  tags:
    - concourse
    - install

# Generate required keys
- name: Generate Host key
  shell: ssh-keygen -t rsa -f host_key -N ''
  args:
    chdir: /opt/concourse/
    creates: host_key
    owner: concourse
    group: concourse

- name: Generate Worker key
  shell: ssh-keygen -t rsa -f worker_key -N ''
  args:
    chdir: /opt/concourse/
    creates: worker_key
    owner: concourse
    group: concourse

- name: Generate Session Signing Key
  shell: ssh-keygen -t rsa -f session_signing_key -N ''
  args:
    chdir: /opt/concourse/
    creates: session_signing_key
    owner: concourse
    group: concourse

# Copy worker key as authorized_worker_keys
- name: Create authorized worker keys
  shell: cp worker_key.pub authorized_worker_keys
  args:
    chdir: /opt/concourse/
    creates: authorized_worker_keys
    owner: concourse
    group: concourse
